### ISSUE TITLE
Error while downloading Kaldi (fr version) : dictionary.txt

### ISSUE THREAD

**Issue by dav-33** [synesthesiam/fr_kaldi-guyot#1]
Trying to add kaldi (fr version) as speech-to-text engine, the web interface asks to download additional files : Rhasspy needs to download some files for your profile (23 missing, 64.9 MiB)
When clicking on download button, this error is raised : DownloadFailedException: ('https://github.com/synesthesiam/fr_kaldi-guyot/raw/master/base_dictionary.txt', 'File size mismatch (got 167756 byte(s), expected 2116243)')
On github there is no more a 'base_dictionary.txt' file but a 'base_dictionary.txt.gz'. Probably the cause of the error

**Comment by synesthesiam** [comment]
Got it, thanks for the catch. A fix is in the pipeline...
